name: lume-model-server-demo
channels:
  - jrgarrahan
  - bokeh
dependencies:
  - python=3.7
  - jupyter_bokeh==2.0.3
  - lume-epics==0.4
  - lume-model==0.2
  - pip
  - pip:
    - tensorflow-cpu==2.3.0
    - jupyter-server-proxy==1.5.0
