name: lume-model-server-demo
dependencies:
  - python=3.7
  - bokeh::jupyter_bokeh
  - jrgarrahan::lume-epics
  - jrgarrahan::lume-model
  - numpy
  - pip
  - pip:
    - tensorflow-cpu
    - jupyter-server-proxy