#!/bin/bash
export EPICS_CA_ADDR_LIST="localhost"
export EPICS_CA_AUTO_ADDR_LIST=NO
python surrogate_model_server.py > server.log 2> server_error.log &
netstat -r > netstat.log
ifconfig eth0 > ifconfig.log
exec "$@"