#!/bin/bash
export EPICS_INTF_CA_ADDR_LIST="localhost"
export EPICS_CA_ADDR_LIST="localhost"
export EPICS_CA_AUTO_ADDR_LIST=NO
python surrogate_model_server.py > server.log 2> server_error.log &
python pre_notebook_test.py > pre_notebook_test
python pre_notebook_with_broadcast.py > pre_notebook_with_broadcast
exec "$@"